Feat service order
projeto-ifpb/pob-project pull request #10
Opened 2022-12-14 14:16 UTC by petersvc

2022-12-17 13:41 UTC, kelvinromero requested changes

2022-12-17 13:41 UTC, kelvinromero commented on src/application/Delete.java
> +            // System.out.println("--->Tutor deleted");
É pra deixar comentado mesmo?

2022-12-17 13:41 UTC, kelvinromero commented on src/busines/Facade.java
> +        // tutor.unbindPets();
É pra ficar comentado mesmo?

2022-12-17 13:41 UTC, kelvinromero commented on src/daojpa/DAOPet.java
> +	public Pet query(Object id) {
Acho que um nome mais adequado seria get não?

2022-12-17 13:41 UTC, kelvinromero commented on src/daojpa/DAOPet.java
> +	public Pet query(Object id) {
Ou, pelo que tava vendo padrão parece ser read, quando é feita a busca por id.

2022-12-17 13:41 UTC, kelvinromero commented on src/daojpa/DAOServiceOrder.java
> +// }
É pra ficar comentado ou pode remover esse código?

2022-12-17 13:41 UTC, kelvinromero commented on src/model/Breed.java
> +    private long version;
Acho que a identação ficou errada aqui

2022-12-17 13:41 UTC, kelvinromero commented on src/model/Employee.java
> +        cascade = jakarta.persistence.CascadeType.ALL
Sei que nossas regras de negócio são arbitrárias, mas acho importante levantar que isso aqui seria ruim, provavelmente ordem de serviço e funcionário nunca seriam deletados no mundo real, porque você quer manter o histórico da operação.

2022-12-17 13:41 UTC, kelvinromero commented on src/model/Person.java
> +public abstract class Person {
Será que essa classe é abstrata mesmo? Já que ela tem métodos croncretos implementados?

2022-12-17 13:41 UTC, kelvinromero commented on src/model/ServiceOrder.java
> +    // }
Deveria estar comentado mesmo?

2022-12-17 13:41 UTC, kelvinromero commented on src/model/Tutor.java
> +    }
Isso é uma boa prática mesmo? Se for para permitir deletar um Tutor, a gente vai ter um problema de pets orfãos

2022-12-17 14:15 UTC, petersvc commented on src/model/Employee.java
> +        cascade = jakarta.persistence.CascadeType.ALL
Verdade, não faz sentido.

2022-12-17 14:17 UTC, petersvc commented on src/model/Person.java
> +public abstract class Person {
Eita, eu tava na dúvida sobre a definição, jurava que era abstrata pelo fato dela nunca ser instanciada diretamente, mas tem isso dos métodos também é? vou corrigir.

2022-12-18 00:17 UTC, petersvc commented on src/model/ServiceOrder.java
> +    // }
apaguei já que a gente não usa data no projeto

2022-12-18 00:18 UTC, petersvc commented on src/model/Breed.java
> +    private long version;
corrigido

2022-12-18 00:18 UTC, petersvc commented on src/daojpa/DAOServiceOrder.java
> +// }
apaguei

2022-12-18 00:18 UTC, petersvc commented on src/daojpa/DAOPet.java
> +	public Pet query(Object id) {
corrigi

2022-12-18 00:18 UTC, petersvc commented on src/busines/Facade.java
> +        // tutor.unbindPets();
tirei

2022-12-18 00:18 UTC, petersvc commented on src/application/Delete.java
> +            // System.out.println("--->Tutor deleted");
tirei

2022-12-18 00:20 UTC, petersvc reviewed
corrigido

2022-12-20 01:15 UTC, kelvinromero approved these changes

2022-12-20 02:12 UTC, merged